# Generated by Django 5.1.4 on 2025-01-29 05:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Основной заголовок'),
        ),
        migrations.AddField(
            model_name='blog',
            name='main_title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Основной заголовок'),
        ),
        migrations.AddField(
            model_name='blog',
            name='main_title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Основной заголовок'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_first_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_first_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_first_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_second_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_second_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_second_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='faq',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='faq',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='faq',
            name='text_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='jihoz',
            name='total_en',
            field=models.CharField(max_length=200, null=True, verbose_name='инструмент'),
        ),
        migrations.AddField(
            model_name='jihoz',
            name='total_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='инструмент'),
        ),
        migrations.AddField(
            model_name='jihoz',
            name='total_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='инструмент'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='job_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='job_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='job_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='ourteam',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='plansedescription',
            name='description_en',
            field=models.CharField(max_length=200, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='plansedescription',
            name='description_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='plansedescription',
            name='description_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='текст'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='job_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='job_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='job_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Работа'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='rezident',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='space',
            name='space_en',
            field=models.CharField(max_length=300, null=True, verbose_name='зона'),
        ),
        migrations.AddField(
            model_name='space',
            name='space_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='зона'),
        ),
        migrations.AddField(
            model_name='space',
            name='space_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='зона'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='duration_en',
            field=models.CharField(blank=True, help_text="Davomiylik, masalan: '1 oy', '3 oy', '1 yil'", max_length=50, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='duration_ru',
            field=models.CharField(blank=True, help_text="Davomiylik, masalan: '1 oy', '3 oy', '1 yil'", max_length=50, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='duration_uz',
            field=models.CharField(blank=True, help_text="Davomiylik, masalan: '1 oy', '3 oy', '1 yil'", max_length=50, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
