# Generated by Django 5.1.4 on 2024-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plansedescription",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуга"},
        ),
        migrations.AlterField(
            model_name="plansedescription",
            name="description",
            field=models.CharField(max_length=200, verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="plansedescription",
            name="description_en",
            field=models.CharField(max_length=200, null=True, verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="plansedescription",
            name="description_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="plansedescription",
            name="description_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="plansedescription",
            name="plans",
            field=models.ManyToManyField(
                related_name="Plansedescriptions",
                to="Collabrium.tarif",
                verbose_name="подписка",
            ),
        ),
    ]
