# Generated by Django 5.1.4 on 2024-12-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="space",
            options={"verbose_name": "Зоны", "verbose_name_plural": "Зоны"},
        ),
        migrations.AlterField(
            model_name="space",
            name="page_slug",
            field=models.SlugField(
                editable=False, unique=True, verbose_name="Слаг страницы"
            ),
        ),
    ]
