# Generated by Django 5.1.4 on 2024-12-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="space",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Collabrium.space",
                verbose_name="Место",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tarif",
            name="duration",
            field=models.CharField(
                blank=True,
                help_text="Davomiylik, masalan: '1 oy', '3 oy', '1 yil'",
                max_length=50,
                null=True,
            ),
        ),
    ]
