<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-12-12 16:07
=======
# Generated by Django 5.1.4 on 2024-12-12 16:07
>>>>>>> 87827dd485845dac01d6740bf09bc167e1e62c68

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('Collabrium', '0001_initial'),
=======
        ("Collabrium", "0001_initial"),
>>>>>>> 87827dd485845dac01d6740bf09bc167e1e62c68
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('page_slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(max_length=300)),
                ('page_slug', models.SlugField(unique=True)),
                ('image', models.URLField()),
=======
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("text", models.TextField()),
                ("page_slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("space", models.CharField(max_length=300)),
                ("page_slug", models.SlugField(unique=True)),
                ("image", models.URLField()),
>>>>>>> 87827dd485845dac01d6740bf09bc167e1e62c68
            ],
        ),
    ]
