# Generated by Django 5.0.6 on 2024-12-13 16:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Часто задаваемые вопросы', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'verbose_name': 'Наша команда', 'verbose_name_plural': 'Наша команда'},
        ),
        migrations.AlterModelOptions(
            name='rezident',
            options={'verbose_name': 'Резидент', 'verbose_name_plural': 'Резидент'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='text_first',
            field=ckeditor.fields.RichTextField(verbose_name='Текст 1'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text_second',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Текст 2'),
            preserve_default=False,
        ),
    ]
