# Generated by Django 5.1.4 on 2024-12-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "verbose_name": "Часто задаваемые вопросы",
                "verbose_name_plural": "Часто задаваемые вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="ourteam",
            options={
                "verbose_name": "Наша команда",
                "verbose_name_plural": "Наша команда",
            },
        ),
        migrations.AlterModelOptions(
            name="rezident",
            options={"verbose_name": "Резидент", "verbose_name_plural": "Резидент"},
        ),
    ]
