# Generated by Django 5.1.4 on 2024-12-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0002_alter_space_options_alter_space_page_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="is_potkast",
        ),
    ]
