# Generated by Django 5.0.6 on 2024-12-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0002_faq_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Faq', 'verbose_name_plural': 'Faqs'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ImageField(upload_to='Images/space'),
        ),
    ]
