# Generated by Django 5.0.6 on 2024-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0002_alter_space_options_alter_space_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='page_slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Слаг страницы'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='page_slug',
            field=models.SlugField(blank=True, editable=False, unique=True, verbose_name='Слаг страницы'),
        ),
    ]
