# Generated by Django 5.0.6 on 2024-12-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0002_alter_plansedescription_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
