# Generated by Django 5.1.4 on 2024-12-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0002_podkast"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podkast",
            options={"verbose_name": "Подкаст", "verbose_name_plural": "Подкаст"},
        ),
    ]
