# Generated by Django 5.1.4 on 2024-12-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0003_remove_space_is_potkast"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jihoz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.CharField(max_length=200, verbose_name="инструмент")),
                (
                    "total_uz",
                    models.CharField(
                        max_length=200, null=True, verbose_name="инструмент"
                    ),
                ),
                (
                    "total_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="инструмент"
                    ),
                ),
                (
                    "total_ru",
                    models.CharField(
                        max_length=200, null=True, verbose_name="инструмент"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="Images/podkast", verbose_name="изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкаст",
                "verbose_name_plural": "Подкасты",
            },
        ),
        migrations.DeleteModel(
            name="Podkast",
        ),
        migrations.AlterField(
            model_name="space",
            name="page_slug",
            field=models.SlugField(unique=True, verbose_name="Слаг страницы"),
        ),
        migrations.AddField(
            model_name="jihoz",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jihozlar",
                to="Collabrium.space",
                verbose_name="Связанное пространство",
            ),
        ),
    ]
