# Generated by Django 5.0.6 on 2024-12-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0003_alter_faq_options_alter_space_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_cover', models.ImageField(upload_to='Blog_images')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('page_slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='image',
            field=models.ImageField(upload_to='OurTeam_images'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='job',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rezident',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rezident',
            name='image',
            field=models.ImageField(upload_to='rezident_images'),
        ),
        migrations.AlterField(
            model_name='rezident',
            name='job',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rezident',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
