# Generated by Django 5.0.6 on 2024-12-23 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarif',
            options={'verbose_name': 'Определение', 'verbose_name_plural': 'Определения'},
        ),
        migrations.AlterField(
            model_name='tarif',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='определения', to='Collabrium.space'),
        ),
    ]
