# Generated by Django 5.1.4 on 2024-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0003_alter_podkast_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podkast",
            options={"verbose_name": "Подкаст", "verbose_name_plural": "Подкасты"},
        ),
        migrations.AlterModelOptions(
            name="space",
            options={"verbose_name": "Место", "verbose_name_plural": "Места"},
        ),
        migrations.AddField(
            model_name="space",
            name="is_potkast",
            field=models.BooleanField(default=False, verbose_name="Это подкаст"),
        ),
        migrations.AlterField(
            model_name="podkast",
            name="image",
            field=models.ImageField(
                upload_to="Images/podkast", verbose_name="изображение"
            ),
        ),
    ]
