# Generated by Django 5.1.4 on 2024-12-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0004_jihoz_delete_podkast_alter_space_page_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jihoz",
            old_name="image",
            new_name="img",
        ),
    ]
