# Generated by Django 5.0.6 on 2024-12-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0004_alter_tarif_options_alter_tarif_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='duration',
            field=models.CharField(blank=True, help_text="Davomiylik, masalan: '1 oy', '3 oy', '1 yil'", max_length=50, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='duration_en',
            field=models.CharField(blank=True, help_text="Davomiylik, masalan: '1 oy', '3 oy', '1 yil'", max_length=50, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='duration_ru',
            field=models.CharField(blank=True, help_text="Davomiylik, masalan: '1 oy', '3 oy', '1 yil'", max_length=50, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='duration_uz',
            field=models.CharField(blank=True, help_text="Davomiylik, masalan: '1 oy', '3 oy', '1 yil'", max_length=50, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
