# Generated by Django 5.0.6 on 2024-12-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0004_blog_alter_ourteam_description_alter_ourteam_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourteam',
            options={'verbose_name': 'OurTeam', 'verbose_name_plural': 'OurTeams'},
        ),
        migrations.AlterModelOptions(
            name='rezident',
            options={'verbose_name': 'Rezident', 'verbose_name_plural': 'Rezidents'},
        ),
    ]
