# Generated by Django 5.1.4 on 2024-12-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Collabrium", "0005_rename_image_jihoz_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jihoz",
            old_name="img",
            new_name="image",
        ),
    ]
