# Generated by Django 5.0.6 on 2024-12-23 11:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collabrium', '0005_alter_tarif_duration_alter_tarif_duration_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='text_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='plansedescription',
            name='plans',
            field=models.ManyToManyField(related_name='Plansedescriptions', to='Collabrium.tarif', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Определения', to='Collabrium.space'),
        ),
    ]
